source 'https://rubygems.org'
source 'https://rails-assets.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'dotenv-rails', '2.1.1', require: 'dotenv/rails-now' # load ENV from .env

gem 'rails', '~> 5.1.0.beta1'
gem 'pg', '0.18.2'

gem 'semantic-rails-ui'   # semantic-ui + simple_form + rails helpers

gem 'webpacker', github: 'rails/webpacker'

gem 'hiredis', '0.6.1'
gem 'redis', '3.3.1', require: %w(redis redis/connection/hiredis)
gem 'redis-rails', '5.0.1'

gem 'sidekiq', '4.1.1'    # backgroud jobs
gem 'sidekiq-scheduler', '2.0.6'  # scheduled background jobs
gem 'redis-namespace', '1.5.2'    # share same redis instance for multiple applications
gem 'sinatra', '2.0.0.beta2', :require => false    # for sidekiq-web

gem 'puma', '~> 3.7'

gem 'railman-deployment', '~> 0.2'   # capistrano deployment

gem 'exception_notification', '4.2.1' # exception notification per email

gem 'lograge', '~> 0.4.1'  # one-line-per-request log messages

group :development do
  gem 'better_errors'   # better error pages in development
  gem 'binding_of_caller'   # repl on the error page
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate', '~> 2.7.1'   # add comments to models with db column information
  gem 'letter_opener', '1.4.1'    # for email tests in development
  # gem 'rack-mini-profiler'
  # gem 'flamegraph'    # mini-profiler flamegraph extension (?pp=flamegraph)
end

group :test do
  gem 'minitest-reporters', '1.1.7'   # generate xml for jenkins
  gem 'minitest-screenshot-reporter', '0.0.2'   # generate screenshots on capybara errors
  gem 'simplecov', require: false     # generate coverage reports
  gem 'simplecov-rcov', '0.2.3', require: false   # generate coverage reports for jenkins
  gem 'capybara', '2.12.1'   # dsl for browser tests
  gem 'capybara_minitest_spec', '1.0.5'   # capybara rspec-style matchers (must_have...)
  gem 'selenium-webdriver', '3.2.2'      # use real browser for webtests
  gem 'poltergeist', '1.8.1'      # headless tests with phantom.js
  gem 'database_cleaner', '1.5.2'     # cleanup test database after every integration test
end

# put additional application-specific gems to Gemfile.local
local_gemfile = File.join(File.dirname(__FILE__), "Gemfile.local")
eval_gemfile(local_gemfile) if File.exists?(local_gemfile)

