# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d30cb11360698947e61366f97fcf7c7cabb5910664a469b25c3ad306588a649866db362a0ccd25ffc2e323e8932094eddff1b625767a1f67b06678904373be

test:
  secret_key_base: 2da22713e498d86b95434e0f0e90152b51db5859087c0ae8612a48105649820bb7e3f168b8531ce8f09ef4ce9840a03a8e08dceb5cb4bb104f3f00aaeff8c3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
